apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "max-age-machines-pruner.fullname" . }}-script
  labels:
  {{- include "max-age-machines-pruner.labels" . | nindent 4 }}
data:
  max_age_machine_pruner.py: |
  {{ $.Files.Get "src/main.py" | nindent 4 }}