# ------------------------------------------------------------------------------
# Opinionated defaults for aged-machines-pruner.
# ------------------------------------------------------------------------------

# Openshift built-in cli image,
# quay.io/openshift/origin-cli would be fine too.
# Image should contain oc (openshift cli) binary and python 3.6+
image: "image-registry.openshift-image-registry.svc:5000/openshift/cli"
imageTag: "latest"
imagePullPolicy: IfNotPresent
imagePullSecrets: []


maxAgeMachinePruner:
  pod:
    nodeSelector:
      node-role.kubernetes.io/master: ""
    tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
    affinity: {}
  schedule: "0 0 * * MON"
  suspend: false

  DRY_RUN: false
  MACHINE_MAX_AGE_HOURS: 10
  ADDITIONAL_FILTER_LABELS: ""
  MAX_DELETING_AT_ONCE: 1


rbac:
  serviceAccount:
    # Specifies whether a service account should be created
    create: true
    # Annotations to add to the service account
    annotations: {}
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: ""
  roles:
    # will create role and rolebinding wihtin openshift-machine-api namespace for allow to list and delete machines
    create: true
    machineApiNamespace: "openshift-machine-api"
    # Annotations to add to the role and rolebinding
    annotations: { }

