apiVersion: v1
kind: ServiceAccount
metadata:
  name: machine-max-age-pruner
  namespace: machine-max-age-pruner

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: machine-max-age-pruner
  namespace: machine-max-age-pruner
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
rules:

  - apiGroups:
      - machine.openshift.io
    resources:
      - machines
    verbs:
      - get
      - list
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: machine-max-age-pruner
  namespace: machine-max-age-pruner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: machine-max-age-pruner
subjects:
  - kind: ServiceAccount
    name: machine-max-age-pruner
    namespace: machine-max-age-pruner